package vista;

import controlador.DAOModoPago;
import controlador.DAOProducto;
import controlador.DAOVenta;
import modelo.ModoPago;
import modelo.Producto;
import modelo.Venta;
import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.SQLException;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author gabriel rivas
 */

public class JFrameVenta extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;

    private DefaultTableModel modeloTablaVenta;
    private Object[] objetoVentaTabla = new Object[6];
    private Double total = 0.0;
    private int item = 0;
    private java.sql.Date fech;
    private int numfac = 0;
    private int cantidad = 0;
    private int idproducto;

    public JFrameVenta() throws SQLException {

        initComponents();
        jDialogProducto.setSize(100, 100);
        ObtenerProductos();
        this.setSize(1920, 1080);
        this.setLocationRelativeTo(null); // Centra el JFrame en la pantalla
        jTextCantProducto.setText("0");
        jDialogProducto.setLocationRelativeTo(null);
        jTextIdProducto.setEnabled(false);
        fech = java.sql.Date.valueOf(LocalDate.now());
        jLabelFecha.setText(fech.toString());
        this.mostrarImagen(jLabelBack,
                "src\\Imagenes\\Back.png");
        setIconImage(new ImageIcon(getClass().getResource("/Imagenes/Icono.png")).getImage());

        try {
            llenarCombModoPago();

        } catch (SQLException ex) {
            Logger.getLogger(JFrameVenta.class.getName()).log(Level.SEVERE, null, ex);
        }

        modeloTablaVenta = (DefaultTableModel) jTableProductosVenta.getModel();
    }

    //================================================================================//
    private void ObtenerProductos() throws SQLException {

        List<Producto> proo = new DAOProducto().ObtenerProducto();

        DefaultTableModel modelo = new DefaultTableModel();
        String[] columnas = {"ID_Producto", "Producto", "Precio", "Existencia"};

        modelo.setColumnIdentifiers(columnas);
        for (Producto pr : proo) {

            String[] renglon = {Integer.toString(pr.getId_producto()), pr.getNombreProducto(), Double.toString(pr.getPrecio()), Integer.toString(pr.getExistencia())};
            modelo.addRow(renglon);
        }
        jTableBuscarProducto.setModel(modelo);

    }
    //================================================================================//

    public void limpiarCamposProductos() {
        jTextIdProducto.setText("ID");
        jTextproducto.setText(" ");
        jTextPrecio.setText(" ");
        jTextExistenciaProducto.setText(" ");
        jTextCantProducto.setText(" ");
    }

    //================================================================================//
    public void llenarCombModoPago() throws SQLException {

        List<ModoPago> modoPago = new DAOModoPago().ObtenerDatos();
        for (int i = 0; i < modoPago.size(); i++) {

            jComboModoPago.addItem(new ModoPago(modoPago.
                    get(i).getNum_pago(),
                    modoPago.get(i).getNombreModoP()));
        }
    }

    //================================================================================//
    private void buscarDatosProductos(String dato) throws SQLException {
        List<Producto> productos = new DAOProducto().busquedaProducto(dato);

        DefaultTableModel modelo = new DefaultTableModel();

        String[] columnas = {"id_producto", "Producto", "Precio", "Existencia"};

        modelo.setColumnIdentifiers(columnas);
        for (Producto pro : productos) {

            String[] renglon = {
                Integer.toString(pro.getId_producto()),
                pro.getNombreProducto(),
                Double.toString(pro.getPrecio()),
                Integer.toString(pro.getExistencia())
            };
            modelo.addRow(renglon);
        }
        jTableBuscarProducto.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialogProducto = new javax.swing.JDialog();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jTextDbuscarProducto = new javax.swing.JTextField();
        jBDbuscarProducto = new javax.swing.JButton();
        jBDagregarProducto = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableBuscarProducto = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jTextIdProducto = new javax.swing.JTextField();
        jTextPrecio = new javax.swing.JTextField();
        jTextproducto = new javax.swing.JTextField();
        jTextExistenciaProducto = new javax.swing.JTextField();
        jTextCantProducto = new javax.swing.JTextField();
        jBagregarProducto = new javax.swing.JButton();
        jBquitaProducto = new javax.swing.JButton();
        jBbuscarProducto = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboModoPago = new javax.swing.JComboBox<>();
        jBguardarVenta = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jLabelFecha = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelBack = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableProductosVenta = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();

        jPanel7.setBackground(new java.awt.Color(211, 217, 254));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel3.setText("Buscar Producto");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 36, -1, -1));

        jPanel6.setBackground(new java.awt.Color(159, 175, 254));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(14, 94, 237), 5));

        jTextDbuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDbuscarProductoActionPerformed(evt);
            }
        });
        jTextDbuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextDbuscarProductoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextDbuscarProductoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextDbuscarProductoKeyTyped(evt);
            }
        });

        jBDbuscarProducto.setText("Buscar");
        jBDbuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDbuscarProductoActionPerformed(evt);
            }
        });

        jBDagregarProducto.setText("Añadir");
        jBDagregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDagregarProductoActionPerformed(evt);
            }
        });

        jButton1.setText("Reiniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTableBuscarProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Existencia"
            }
        ));
        jScrollPane3.setViewportView(jTableBuscarProducto);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jTextDbuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBDbuscarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBDagregarProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(41, 41, 41))
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextDbuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBDbuscarProducto)
                    .addComponent(jBDagregarProducto)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 630, 250));

        javax.swing.GroupLayout jDialogProductoLayout = new javax.swing.GroupLayout(jDialogProducto.getContentPane());
        jDialogProducto.getContentPane().setLayout(jDialogProductoLayout);
        jDialogProductoLayout.setHorizontalGroup(
            jDialogProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 745, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialogProductoLayout.setVerticalGroup(
            jDialogProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(211, 217, 254));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(159, 175, 254));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37, 108, 240), 5));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextIdProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextIdProducto.setText("ID");
        jTextIdProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextIdProductoActionPerformed(evt);
            }
        });
        jPanel4.add(jTextIdProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 70, 31));

        jTextPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(jTextPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 103, 33));

        jTextproducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextproductoActionPerformed(evt);
            }
        });
        jPanel4.add(jTextproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 100, 290, 31));

        jTextExistenciaProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(jTextExistenciaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 133, 33));

        jTextCantProducto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTextCantProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCantProductoActionPerformed(evt);
            }
        });
        jPanel4.add(jTextCantProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 107, 33));

        jBagregarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBagregarProducto.setText("Añardir");
        jBagregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBagregarProductoActionPerformed(evt);
            }
        });
        jPanel4.add(jBagregarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 88, 33));

        jBquitaProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBquitaProducto.setText("Quitar");
        jBquitaProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBquitaProductoActionPerformed(evt);
            }
        });
        jPanel4.add(jBquitaProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 88, 33));

        jBbuscarProducto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBbuscarProducto.setForeground(new java.awt.Color(0, 0, 0));
        jBbuscarProducto.setText("Buscar");
        jBbuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBbuscarProductoActionPerformed(evt);
            }
        });
        jPanel4.add(jBbuscarProducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 100, 88, 31));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Codigo");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Existencia");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nombre del producto ");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Precio");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("Cantidad a retirar");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        jLabel10.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 18)); // NOI18N
        jLabel10.setText("Datos del producto ");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 210, 30));

        jLabel6.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel6.setText("Modo de Pago");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, -1));

        jComboModoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboModoPagoActionPerformed(evt);
            }
        });
        jPanel4.add(jComboModoPago, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, -1, -1));

        jBguardarVenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBguardarVenta.setText("Guardar");
        jBguardarVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBguardarVentaActionPerformed(evt);
            }
        });
        jPanel4.add(jBguardarVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 90, 31));

        jBCancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });
        jPanel4.add(jBCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 90, 31));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 529, 450));

        jLabelFecha.setFont(new java.awt.Font("MS Reference Sans Serif", 2, 18)); // NOI18N
        jLabelFecha.setText("Fecha");
        jPanel1.add(jLabelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(1400, 20, 151, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 36)); // NOI18N
        jLabel5.setText("Sistema de ventas");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 430, 40));

        jLabelBack.setText("jLabel11");
        jLabelBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelBackMouseClicked(evt);
            }
        });
        jPanel1.add(jLabelBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 30, 30));

        jPanel2.setBackground(new java.awt.Color(14, 94, 237));

        jTableProductosVenta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(37, 108, 240)));
        jTableProductosVenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTableProductosVenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object[][] {}, // Arreglo de datos vacío, sin filas
            new String[] { "Items", "Código", "Producto", "Cantidad", "Precio", "Subtotal" } // Nombre de las columnas

        ));
        jScrollPane4.setViewportView(jTableProductosVenta);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 300, 660, 450));

        jLabel8.setFont(new java.awt.Font("MS Reference Sans Serif", 1, 14)); // NOI18N
        jLabel8.setText("Total:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 760, -1, -1));

        jLabelTotal.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        jLabelTotal.setText("0");
        jPanel1.add(jLabelTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(1330, 760, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1920, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1080, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextproductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextproductoActionPerformed

    private void jTextIdProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextIdProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextIdProductoActionPerformed

    //=====================================================================================//
    private void jBbuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBbuscarProductoActionPerformed
        try {
            ObtenerProductos();
        } catch (SQLException ex) {
            Logger.getLogger(JFrameVenta.class.getName()).log(Level.SEVERE, null, ex);
        }

        jDialogProducto.setSize(680, 400);
        jDialogProducto.setVisible(true);
        jDialogProducto.setLocationRelativeTo(null);
        // TODO add your handling code here:
    }//GEN-LAST:event_jBbuscarProductoActionPerformed
    //=========================================================================================//
    private void jBDbuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDbuscarProductoActionPerformed

        if (jTextDbuscarProducto.getText().contentEquals("")) {
            JOptionPane.showMessageDialog(rootPane, "Ingrese un producto");
            try {
                ObtenerProductos();
            } catch (SQLException ex) {
                Logger.getLogger(JFrameVenta.class.getName()).log(Level.SEVERE, null, ex);
            }

        } else {
            try {
                String datoprod = jTextDbuscarProducto.getText();

                buscarDatosProductos(datoprod);
                jTextDbuscarProducto.setText("");

            } catch (SQLException ex) {
                Logger.getLogger(JFrameVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jBDbuscarProductoActionPerformed

    //=========================================================================================//
    private void jBDagregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDagregarProductoActionPerformed

        int fila = this.jTableBuscarProducto.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione un registro de la tabla");
        } else {
            try {
                int id = Integer.parseInt((String) this.jTableBuscarProducto.
                        getValueAt(fila, 0).toString());

                String nom = (String) this.jTableBuscarProducto.getValueAt(fila, 1);

                double pre = Double.parseDouble((String) this.jTableBuscarProducto.
                        getValueAt(fila, 2).toString());

                int Exis = Integer.parseInt((String) this.jTableBuscarProducto.
                        getValueAt(fila, 3).toString());

                // --------------- se ubican las cajas de texto lo datos capturados ----------//
                jTextIdProducto.setText("" + id);
                jTextproducto.setText(nom);
                jTextPrecio.setText("" + pre);
                jTextExistenciaProducto.setText("" + Exis);

                jDialogProducto.dispose();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Ocurrio un ERROR" + e.getMessage());
            }

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBDagregarProductoActionPerformed

    //=========================================================================================//
    private void jBagregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBagregarProductoActionPerformed

         // Obtener la cantidad disponible desde la base de datos para el producto (por ejemplo, usando un método de consulta SQL)
    int  cantidadDisponible = Integer.parseInt(jTextExistenciaProducto.getText().trim());

    // Obtener la cantidad solicitada por el usuario
    int cantidadSolicitada = Integer.parseInt(jTextCantProducto.getText().trim());
    
    
     // Validar que la cantidad solicitada no sea mayor que la cantidad disponible en el inventario
    if (cantidadSolicitada <= 0) {
        JOptionPane.showMessageDialog(rootPane, "La cantidad solicitada debe ser mayor que 0.");
    } else if (cantidadSolicitada > cantidadDisponible) {
        JOptionPane.showMessageDialog(rootPane, "No hay suficientes productos en stock. Cantidad disponible: " + cantidadDisponible);
    } else {
        item += 1;
        


            objetoVentaTabla[0] = item;

            objetoVentaTabla[1] = jTextIdProducto.getText().trim();
            objetoVentaTabla[2] = jTextproducto.getText().trim();
            objetoVentaTabla[3] = jTextCantProducto.getText().trim();
            objetoVentaTabla[4] = jTextPrecio.getText().trim();

            Double subtotal = Double.parseDouble(jTextCantProducto.getText().trim())
                    * Double.parseDouble(jTextPrecio.getText().trim());

            objetoVentaTabla[5] = subtotal;

            total += subtotal;

            jLabelTotal.setText(total.toString());

            modeloTablaVenta.addRow(objetoVentaTabla);

            limpiarCamposProductos();
            

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_jBagregarProductoActionPerformed

    //==============================================================================//
    private void jBguardarVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBguardarVentaActionPerformed

        try {
            guardarVenta();
            total = 0.0;
            jLabelTotal.setText(total.toString());

        } catch (SQLException ex) {
            Logger.getLogger(JFrameVenta.class.getName()).
                    log(Level.SEVERE, null, ex);
        }
        
        DAOVenta daoventa = new DAOVenta();
        try {
            daoventa.factura();
        } catch (JRException ex) {
            Logger.getLogger(JFrameVenta.class.getName()).log(Level.SEVERE, null, ex);

        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jBguardarVentaActionPerformed

    //=============================================================================//
    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        int n = 0;
        limpiartabla();
    }//GEN-LAST:event_jBCancelarActionPerformed

    //==============================================================================//
    
    private void jBquitaProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBquitaProductoActionPerformed
        int fila = this.jTableBuscarProducto.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(rootPane, "Seleccione una fila a quitar de la tabla");

        } else {
            JDialog.setDefaultLookAndFeelDecorated(true);

            int resp = JOptionPane.showConfirmDialog(null, "¿Esta seguro de quitar el producto de la lista?",
                    "Aceptar", JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);

            if (resp == JOptionPane.NO_OPTION) {
                JOptionPane.showMessageDialog(rootPane, "no se ha retirado ningun producto");

            } else {
                if (resp == JOptionPane.YES_OPTION) {
                    DefaultTableModel temp = (DefaultTableModel) jTableProductosVenta.getModel();

                    temp.removeRow(fila);
                    for (int i = 0; i < jTableProductosVenta.getRowCount(); i++) {
                        total = 0.0;
                        total += Double.parseDouble(jTableProductosVenta.getValueAt(i, 5).toString());

                    }
                    jLabelTotal.setText(total.toString());
                }
            }
            if (resp == JOptionPane.CLOSED_OPTION) {
                JOptionPane.showMessageDialog(rootPane, "ninguna accion realizada");
            }
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jBquitaProductoActionPerformed

    //=======================================================================================//
    private void jComboModoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboModoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboModoPagoActionPerformed


    private void jTextCantProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCantProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCantProductoActionPerformed

    //=======================================================================================//
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            ObtenerProductos();

            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(JFrameVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    //=======================================================================================//
    private void jLabelBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBackMouseClicked

        JframeHome _home = new JframeHome(); // TODO add your handling code here:
        _home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabelBackMouseClicked

    //=======================================================================================//
    private void jTextDbuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDbuscarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDbuscarProductoActionPerformed

    private void jTextDbuscarProductoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDbuscarProductoKeyPressed
    }//GEN-LAST:event_jTextDbuscarProductoKeyPressed

    private void jTextDbuscarProductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDbuscarProductoKeyTyped

        



        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDbuscarProductoKeyTyped

    
    //=======================================================================================//
    private void jTextDbuscarProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextDbuscarProductoKeyReleased
         String datoprod = jTextDbuscarProducto.getText().trim();
    
    if (datoprod.isEmpty()) {
        // Si el campo de búsqueda está vacío, muestra todos los productos o un mensaje
        try {
            ObtenerProductos();
        } catch (SQLException ex) {
            Logger.getLogger(JFrameVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    } else {
        // Realiza la búsqueda dinámica según el texto ingresado
        try {
            buscarDatosProductos(datoprod);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameVenta.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDbuscarProductoKeyReleased
//=======================================================================================//
    public void guardarDetalleVenta() throws SQLException {

        double precio;

    if (numfac == 0 || jTableProductosVenta.getRowCount() == 0) {
        JOptionPane.showMessageDialog(rootPane, "No se ha obtenido número de factura o no tiene productos añadidos para vender");
        return; // Salir si no hay datos válidos
    }

    boolean huboError = false; // Iniciar como false, cambiar a true si ocurre algún error

    try {
        for (int i = 0; i < jTableProductosVenta.getRowCount(); i++) {

            int idproducto = Integer.parseInt(jTableProductosVenta.getValueAt(i, 1).toString());
            int cantidad = Integer.parseInt(jTableProductosVenta.getValueAt(i, 3).toString());
            precio = Double.parseDouble(jTableProductosVenta.getValueAt(i, 4).toString());

            Venta detalleventa = new Venta(numfac, idproducto, cantidad, precio);

            DAOVenta daoDetalleVenta = new DAOVenta();
            
            // Intentar insertar el detalle de venta
            if (daoDetalleVenta.insertarDetalleVenta(detalleventa) != 0) {
                huboError = true; // Marcar error si no se pudo insertar el detalle
            }
        }
    } catch (SQLException | NumberFormatException ex) {
        Logger.getLogger(JFrameVenta.class.getName()).log(Level.SEVERE, null, ex);
        huboError = true; // Marcar error si hay una excepción
    }

    // Mostrar mensaje de éxito o error después de procesar todos los productos
    if (huboError) {
        JOptionPane.showMessageDialog(rootPane, "Ocurrió un error al procesar algunos productos.", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(rootPane, "Venta guardada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        limpiartabla();
    }

        

    }
    //=======================================================================================//

    public void limpiartabla() {
        DefaultTableModel model = (DefaultTableModel) jTableProductosVenta.getModel();
    model.setRowCount(0); // Borra todas las filas
    }
//=======================================================================================//
    public void actualizaExistencia() {
        int existenciaActual;
        int nuevaExistencia;

        for (int i = 0; i < jTableProductosVenta.getRowCount(); i++) {
            idproducto = Integer.parseInt(jTableProductosVenta.
                    getValueAt(i, 1).toString());
            cantidad = Integer.parseInt(jTableProductosVenta.
                    getValueAt(i, 3).toString());

            DAOProducto daopro = new DAOProducto();
            try {
                List<Producto> p = daopro.busquedaProducto(String.valueOf(idproducto).toString());

                if (p.isEmpty()) {
                    // Manejar el caso donde no se encuentra el producto
                    JOptionPane.showMessageDialog(rootPane, "Producto no encontrado para el ID: " + idproducto);
                    continue; // Saltar a la siguiente iteración
                }

                existenciaActual = p.get(0).getExistencia();

                nuevaExistencia = existenciaActual - cantidad;

                Producto pro = new Producto(idproducto, nuevaExistencia);

                DAOVenta daoVenta = new DAOVenta();

                if (daoVenta.actualizarExistenciaProductos(pro) == 0) {
                    //   JOptionPane.showMessageDialog(rootPane, "Existencia Actualizada");

                }

            } catch (SQLException ex) {
                Logger.getLogger(JFrameVenta.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    //=======================================================================================//

    public void guardarVenta() throws SQLException {
        int numpago = 0, idcliente;

        numpago = jComboModoPago.getItemAt(jComboModoPago.getSelectedIndex())
                .getNum_pago();

        if (jLabelFecha.getText().contentEquals("")
                || numpago == 0 || jTableProductosVenta.getRowCount() == 0) {

           
        }
         try {
        // Crear el objeto Venta con los datos necesarios
        Venta vent = new Venta(numpago, fech);

        // Instancia de DAOVenta
        DAOVenta daoventa = new DAOVenta();

        // Insertar la venta en la base de datos
        if (daoventa.insertarVenta(vent) == 0) {
            // Si la inserción es exitosa, obtener el número de factura
            numfac = daoventa.obtenerUltimoNumFactura();
             actualizaExistencia();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Ha ocurrido un error, no se insertó la venta");
            return;  // Salir del método si no se insertó la venta correctamente
        }

    } catch (HeadlessException | SQLException e) {
        JOptionPane.showMessageDialog(rootPane, "Error al guardar la venta: " + e.getMessage());
        return;  // Salir del método si ocurre una excepción
    }

    try {
        // Guardar los detalles de la venta
        guardarDetalleVenta();

       
       

                
    } catch (SQLException e) {
        JOptionPane.showMessageDialog(rootPane, "Error al guardar los detalles de la venta o actualizar existencias: " + e.getMessage());
    }
}
        //=======================================================================================//

    

    private void mostrarImagen(JLabel lbl, String ruta) {
        this.imagen = new ImageIcon(ruta);
        this.icono = new ImageIcon(
                this.imagen.getImage().getScaledInstance(
                        lbl.getWidth(),
                        lbl.getHeight(),
                        Image.SCALE_DEFAULT));
        lbl.setIcon(this.icono);
        this.repaint();

    }
//=======================================================================================//
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */

        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameVenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFrameVenta().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JFrameVenta.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBDagregarProducto;
    private javax.swing.JButton jBDbuscarProducto;
    private javax.swing.JButton jBagregarProducto;
    private javax.swing.JButton jBbuscarProducto;
    private javax.swing.JButton jBguardarVenta;
    private javax.swing.JButton jBquitaProducto;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<ModoPago> jComboModoPago;
    private javax.swing.JDialog jDialogProducto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelBack;
    private javax.swing.JLabel jLabelFecha;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTableBuscarProducto;
    private javax.swing.JTable jTableProductosVenta;
    private javax.swing.JTextField jTextCantProducto;
    private javax.swing.JTextField jTextDbuscarProducto;
    private javax.swing.JTextField jTextExistenciaProducto;
    private javax.swing.JTextField jTextIdProducto;
    private javax.swing.JTextField jTextPrecio;
    private javax.swing.JTextField jTextproducto;
    // End of variables declaration//GEN-END:variables

}
